### ISSUE TITLE
Could we have some off line installers?

### ISSUE THREAD

**Issue by StephenR0** [ljani/emby-portable-links#1]
Your web site is down and I have no way to install the server or Media Browser Classic.  Do we have to rely on your web server?  What about some mirrors?

**Comment by StephenR0** [comment]
I'm sorry, you're not the right one to complain to.

**Comment by ljani** [comment]
Hey. Yeah, it seems http://www.emby.media is down as well as their distribution site http://www.mb3admin.com is too. I should change the error message.

Let me reopen this and think of a better message.
